### ISSUE TITLE
Amend the template to include new sections

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythiaCookbooks/cookbook-template#2]
Per our discussion at the last infrastructure meeting on 4/7/22 ([see notes here](https://docs.google.com/document/d/1lIioFOGvKsQDyfq0_kCecWcDYiH4HGip_whHo__9THU/edit#heading=h.jrmcikkzlw6b)), it would be nice to add some sections to the cookbook template for content like:

- Foundational material (e.g., Foundations-like content that extends what is in the Pythia Foundations book)
- Examples (e.g., specific examples using the content detailed in the Foundational material section)

**Comment by r-ford** [comment]
I believe this is done with #12.
