### ISSUE TITLE
Move config, toc, and landing page to root

### ISSUE THREAD

**Issue by mgrover1** [ProjectPythiaCookbooks/cookbook-template#28]
We should move the configuration file, table of contents, and landing page files to the root directory. Also, since the "landing page" is identical to the README in the radar cookbook, it would make sense to sync the README and landing page.

This would mean the badges would appear on the book landing page too!

**Comment by brian-rose** [comment]
Some of the workflows in the `.github/workflows/` directory will need paths updated.

**Comment by mgrover1** [comment]
Once you move the `_toc.yml` and `_config.yml` files to the root directory, you will need to make the following changes to your files:
- `_toc.yml` - make sure that **any path to content in `/notebooks` includes `notebooks` at the beginning of the path (ex. `foundations/pyart-basics.ipynb` --> `notebooks/foundations/pyart-basics.ipynb`)
  - Don't forget the images here too, and move the `landing-page.md` to the root directory and rename to `README.md`, including the badges in the template
- `_config.yml` - update the path to the images (ex. ARM logo) to the proper path in the `notebooks/` directory
- Github actions in `.github/workflows/`
  - Here is a list of files that need the path to the notebooks updated
  ```
  .
├── dependabot.yml
└── workflows
    ├── build-book.yaml
    ├── delete-preview.yaml
    ├── deploy-book.yaml - update path_to_notebooks, unzip notebook path, and publish directory 
    ├── deploy-preview.yaml
    ├── link-checker.yaml
    ├── nightly-build.yaml - update path_to_notebooks
    └── trigger-book-build.yaml - update path_to_notebooks
  ```

All these changes will be reflected in the template, but these are changes that you will need to make if you have already forked the repository.

**Comment by jukent** [comment]
Adding that we will also have to change the cookbook navbar link in the `_config.yml` file again with the new ProjectpythiaCookbooks domain!

**Comment by brian-rose** [comment]
Will close this since the changes have all been made in the Template repo. I still haven't update the Physical Oceanography repo.
